Dockerized the repository using Docker Compose
oss-slu/dads pull request #107
Opened 2024-03-04 17:54 UTC by LaxminarayanaV7416

Fixes #103 

**What was changed?**

* Added the new docker-compose.yaml file and with the configuration to spin up all the containers at once.*
* There are respective Dockerfiles in the respective backend and frontend directories as they are different environments.*
* made some code chages in both backend and frontend to incorporate the incoming environmental variables while building docker container and this changes also support the legacy development process which we are doing till now using the setup.sh file*

**Why was it changed?**

* Dockerizing the application will ease the development and even the deployment, this approach while deploying is easily scalable.*

**Screenshots that show the changes (if applicable):**

2024-03-20 21:05 UTC, AbhilashKotha requested changes
Hello @LaxminarayanaV7416 Thanks for the changes that you suggested, they definitely add a lot of value to the developers. 

Sorry, I got to the PR late. 

I added some inline comments suggesting some changes. In addition please consider the below points.

The client has moved the data to cloud. The env file should have both the credentials and the developers should have an option to toggle the data source between cloud and local. 

Please fetch the latest changes from main as we merged some PRs

2024-03-20 21:05 UTC, AbhilashKotha commented on Backend/requirements.txt
Keep only those that are needed for the current code to run.

2025-05-09 18:17 UTC, suprajamannava17 commented
The branch currently has conflicts and further refinement may be needed before integration. Closing this issue for now; future work can continue from the current state as needed."

2025-05-09 18:17 UTC, closed without merging

2025-07-15 20:30 UTC, kungfuchicken commented
@suprajamannava17 and @LaxminarayanaV7416 this is still an incredibly valuable pull request, and if you can get the changes integrated it would be a huge help for developers. Worst case we can start it over. I'd like to make sure @LaxminarayanaV7416 get's suitable credit for this contribution, too.