WIP on issue #30 plus styling
oss-slu/dads pull request #80
Opened 2023-11-13 20:22 UTC by lRolwes

Implemented all statistics available in the data, 
Styling on statistics box
Status: stat implemented, styling partially complete

2023-11-18 21:42 UTC, Evan-Richmond approved these changes
Looks great!

2023-11-18 21:42 UTC, Evan-Richmond commented on Backend/PostgresConnector.py
> +        resultant = cur.fetchall()
thanks for fixing naming conventions here, much more clear

2023-11-18 21:42 UTC, Evan-Richmond commented on Frontend/src/pages/AboutPage.js
> +    <h3>Setup Docker Container</h3>
These setup instructions are great, should be easy to replace when we change our database setup

2023-11-20 02:56 UTC, AJelliss approved these changes
Looks Amazing! can't wait to see it merged

2023-11-20 06:20 UTC, AbhilashKotha requested changes
@lRolwes The Home new styles are amazing. Information on the Home page looks great! I just have a few more improvement suggestions. 

1. the statistics div goes to the bottom on my computer.
<img width="1280" alt="image" src="https://github.com/oss-slu/dads/assets/113061137/e6eb970a-1b0a-4046-b452-86e87cb1462b">
<img width="1280" alt="image" src="https://github.com/oss-slu/dads/assets/113061137/8a9abcdf-d207-4585-a62e-f08d2fbaec4e">

2. The Home page has a lot of technical information. Let us assume that not all of our users have technical knowledge and will use the app with a URL after it is hosted. For now, you can just redirect them to a current .md file or you can also create new files for troubleshooting steps. 

so my suggestion would be to move eveything after Github URL to github and add those redirection URLs in the website
3. Increase the font size and font weight for statistics just a little bit.

2023-11-20 19:08 UTC, AbhilashKotha approved these changes

2023-11-20 19:08 UTC, merged