fixing_filters
oss-slu/dads pull request #99
Opened 2024-02-19 19:29 UTC by lRolwes

Fixes #93 

**What was changed?**

*Here, describe what part of the application you changed (e.g. login page, database, etc.). If possible, mention what specific components were added, removed, or modified.*

**Why was it changed?**

*Here, describe the issue that you are fixing with this code, and why your code fixes it.*

**How was it changed?**

*Here, get into detail about what files you modified, and talk about the most important lines in regards to fixing the issue.*

**Screenshots that show the changes (if applicable):**

2024-02-25 21:15 UTC, Evan-Richmond approved these changes
Everything works as expected for me!

2024-02-26 06:21 UTC, AbhilashKotha requested changes
@lRolwes While the changes could work, I think there is a better way to handle this, could you please look at my suggestions. Feel free to reach out if you need more clarity. Thanks.

2024-02-26 06:21 UTC, AbhilashKotha commented on Backend/PostgresConnector.py
> +    def reconnect(self):
We should not have this function. there is a better way to handle this.

2024-02-26 06:21 UTC, AbhilashKotha commented on Backend/PostgresConnector.py
> +        try:
try, except, and finally blocks are good. but in addition, we should use the "with" statement.

2024-02-26 06:21 UTC, AbhilashKotha commented on Backend/PostgresConnector.py
> +            self.reconnect()
reconnect should not be the solution. We should not break the connection in the first place. Please look for the "rollback" command.

2024-02-26 06:21 UTC, AbhilashKotha commented on Frontend/src/pages/ExploreSystems.js
> +            reportMajorError("Error: Issue fetching requested data");
Can we make it more clear, something like..
```suggestion
            reportMajorError("There was an error while fetching the information requested. Please contact the system administrator.");
```

2024-02-26 21:34 UTC, AbhilashKotha commented
@lRolwes Great, this is the approach we need! Just a few more improvements.

Wherever we have a cursor, we will use the "with" statement
Wherever we have a database query, we will use rollback in the except block

2024-02-28 19:25 UTC, merged